config/routes.rb
Test2::Application.routes.draw do

  devise_for :users, skip: :registrations

  devise_scope :user do 
    root :to => "devise/sessions#new"
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
    resources :users
    resources :payments
    get "visits" => 'visits#index'
    get "pending_users" => 'pending_users#index'
    post "pending_users" => 'pending_users#create'

  
  

  

end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :user
	has_one :profile, through: :user
	scope :in_range, ->( start, finish, page_param) { where( created_at: start..finish).page(page_param).order( "created_at DESC" ) }
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :only_allow_admin, only: [:show, :new, :edit, :create, :update, :destroy]
  before_filter :set_payment, only: [:show, :edit, :update, :destroy]
  before_filter(only: :index)  { set_date_user_params('/payments') }
  
  def index
    if current_user.admin?
      if @user
        @payments = @user.payments.in_range( @start_date, @end_date, params[:page] )
      else
        @payments = Payment.includes(:profile).in_range( @start_date, @end_date, params[:page] )
      end
    else
      @payments = current_user.payments.in_range( @start_date, @end_date, params[:page] )
    end
  end

  def show
  end

  def new
    @payment = Payment.new
  end

  def edit
  end

  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payment }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:user_id, :amount, :period, :paid, :paid_on, :invoice)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
	def payment_status
		['Paid','Pending']
	end

	def get_balance
		payment = @payments.find { |e| e.paid == false }
		number_to_currency(payment.amount) unless payment.nil?
	end

	def get_last_payout
		payment = @payments.find { |e| e.paid == true }
		number_to_currency(payment.amount) unless payment.nil?
	end
end

app/views/payments/_form.html.erb
<%= simple_form_for(@payment, html: {class: 'well'}) do |f| %>

  <% if notification = f.error_notification %>
    <div class="alert alert-error fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= notification %>
    </div>
  <% end %>

  <div class="form-inputs">
  	<%= f.input :user_id, collection: get_all_users %>
  	<%= f.input :amount %>
  	<%= f.input :period %>
  	<%= f.input :paid %>
  	<%= f.input :paid_on %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-medium btn-success' %>
  </div>
<% end %>

app/views/payments/_table.html.erb
<table class="table table-striped table-bordered" id="example">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Period</th>
      <th>Status</th>
      <th>Paid on</th>
      <% if is_admin? %>
        <th>Profile</th>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.amount %></td>
        <td><%= payment.period %></td>
        <td>
          <% if payment.paid %>
            Paid
            <td><%= payment.paid_on.strftime("%d/%m/%Y") %></td>
          <% else %>
            Pending
            <td>Pending</td>
          <% end %>
        </td>
        <% if is_admin? %>
          <td>
            <% if !payment.profile.nil? %>
              <%= payment.profile.campaign %>
              <% end %>
          </td>
          <td>
            <%= link_to 'Edit', edit_payment_path(payment) %>
            <%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @payments %>

app/views/payments/edit.html.erb
<% content_for(:title, 'Edit Payment') %>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<% content_for(:title, 'Payments') %>

<%= render partial: 'shared/user_date_form',locals: { path: payments_path } %>

<% if !is_admin? || @user %>
	<div class="row">
		<div class="span6">
			<h3>Balance: <%= get_balance %></h3>
		</div>
		<div class="span6">
			<h3>Last Payout: <%= get_last_payout %></h3>
		</div>
	</div>
<% end %>

<%= render 'table' %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>