config/routes.rb
Test2::Application.routes.draw do

  devise_for :users, skip: :registrations

  devise_scope :user do 
    root :to => "devise/sessions#new"
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
    resources :users
    resources :payments
    get "visits" => 'visits#index'
    get "pending_users" => 'pending_users#index'
    post "pending_users" => 'pending_users#create'

  
  

  

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) and msg.length > 0 %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}"  %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header>
	<div class="navbar navbar-inverse">
	  <div class="navbar-inner">
	    <%= link_to root_path, class: 'brand' do %>
	    	Get Viral <sub>alpha</sub>
	    <% end %>
	    <ul class="nav">
	    	<% if user_signed_in? %>
					<li><%= link_to 'Reports', visits_path %></li>
					<li><%= link_to 'Payments', payments_path %></li>
	    		<% if is_admin? %>
				    <ul class="nav">  				    		
		    		  <li class="dropdown">
		    		    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		    		      Manage Users
		    		      <b class="caret"></b>
		    		    </a>
		    		    <ul class="dropdown-menu">
		    		    	<li><%= link_to 'Add/Edit Users', users_path %></li>
		    		    	<li><%= link_to 'Pending Users', pending_users_path %></li>
		    		    </ul>
		    		  </li>
		    		</ul>
    			<% end %>
  			<% end %>
	    </ul>
	    <ul class="nav pull-right">
	    	<% if user_signed_in? %>
    		  <li class="dropdown">
    		    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    		      <%= current_user.name %>
    		      <b class="caret"></b>
    		    </a>
    		    <ul class="dropdown-menu">
    		    	<li><%= link_to 'Edit Details', edit_user_registration_path() %></li>
    		      <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
    		    </ul>
    		  </li>
    		  <% else %>
    				<li><%= link_to 'Sign in', new_user_session_path %></li>
  			<% end %>
	    </ul>
	  </div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 	<title><%= content_for?(:title) ? yield(:title) + " - " : "" %> Get Viral</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield(:header) if content_for?(:header) %>
</head>
<body>
	<div class="container">
		<%= render 'layouts/navigation' %>
		
		<%= render 'layouts/messages' %>

		<%= yield %>

	</div>
</body>
</html>